### ISSUE TITLE
About your new tracker

### ISSUE THREAD

**Issue by zx007zls** [lvsn/6DOF_tracking_evaluation#1]
Will it be released? (Looking forward to it.)
And will it include the whole training and testing procedure? (I hope so.)
Thanks!

**Comment by MathGaron** [comment]
Hi!
Yes I will release a pytorch version of it, together with the training/testing procedure. However I am busy with a deadline right now, but I may push the code in 1 month. Meanwhile, the training procedure can be found in my previous version (using torch) [here](https://github.com/lvsn/deeptracking). It does not includes the changes from our last paper, but the bulk of the implementation can be found there.
The model will also be much more simple to setup though, as it is not necessary to train from real images.

**Comment by zx007zls** [comment]
@MathGaron I see, thanks for your reply! I will try the new version by then.

**Comment by MathGaron** [comment]
I totally forgot about it! but there it is!
