### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by mir-pias** [lvsn/6DOF_tracking_evaluation#11]
Hello, I wanted to know which tracker is being used in the evaluation scripts provided, generic, multi-object or specific?

**Comment by MathGaron** [comment]
Hey! sorry for the delay I was out of office. The evaluation code does not depend on any tracker, in the end your just provide the ground-truth + predictions from your tracker.

**Comment by mir-pias** [comment]
Hi, thank you for the clarification, one more thing I wanted to ask, the predicted poses provided with object sequences, the `poses.npy` files, which tracker was used to make the predictions?

**Comment by MathGaron** [comment]
There is only the ground truth pose data provided with the sequences.
