### ISSUE TITLE
where are the ao.ply files?

### ISSUE THREAD

**Issue by Guptajakala** [lvsn/6DOF_tracking_evaluation#4]
In the dataset_generator.py file, the "load_ambiant_occlusion_map" needs ao.ply file. When I download the CAD model, I did not find such file. May I ask where I can get it? Thanks in advance!

**Comment by Guptajakala** [comment]
Another thing is in "train_deeptrack.sh" file, 
`OCCLUDER_PATH=/media/mathieu/e912e715-2be7-4fa2-8295-5c3ef1369dd0/dataset/deeptrack_train/hand`
May I ask where I can find the "hand" data?

**Comment by MathGaron** [comment]
Hey,
The ao.ply is the per-vertex ambiant occlusion level. In the CAD models the ambiant occlusions are actually encoded in the vertex color. ao.ply was only used for models that do not use texture but vertex color. Normally everything should still work without an ao.ply, it will simply be ignored by the loader.

For the occluder path, it has to be a folder containing another dataset generated by the same generator. The loader will use this during the training to composite in front of the main object.
If you generate it, just use whatever models as long as they are not too big and do not occlude too much of the object. That said, I will make the one I was using available to help people to reproduce the results!

**Comment by Guptajakala** [comment]
@MathGaron 
Seems like you were using a "hand" object as occluder? Looking forward to your updating your original occluder.
BTW, thank you for such detailed answer and quick response. This is really cool project!

**Comment by MathGaron** [comment]
Thank you!
We just updated the [website](http://vision.gel.ulaval.ca/~jflalonde/projects/6dofObjectTracking/index.html) and added a link to the hand occluder image.
Hope it helps!
