### ISSUE TITLE
Code for prediction

### ISSUE THREAD

**Issue by Guptajakala** [lvsn/6DOF_tracking_evaluation#9]
Hi, Currently I cannot find any code for prediction purpose. I have finished training the model but confused about the implementation about using the trained model for prediction. Are you planning to release the code some time?

**Comment by MathGaron** [comment]
Hey, sorry for some reason this issue totally went out of my radar. I currently don't have a lot of time for this project, however I see that this is a big limitation and I will try to put it higher on my priority list. Meanwhile (this code)[https://github.com/lvsn/deeptracking/blob/master/test_sequence.py] is almost the implementation you need. You can use this to help yourself with generating the csv.

The csv simply have one 4x4 transform matrix per line (each line representing a frame) You can use the Transform utility class to generate the matrix and then flatten it to a list.

**Comment by Guptajakala** [comment]
@MathGaron Thank you! This is helpful
